fig = uifigure();
dropdown = uidropdown(fig, 'Position', [100, 100, 200, 25], ...
    'Items', {'Motor1.rse', 'Motor2.rse', 'Motor3.rse'}, ...
    'ValueChangedFcn', @(dd, event) disp(['Selected: ', dd.Value]));
